openapi: 3.0.0
info:
  description: Map API
  version: "1.0.0"
  title: Map API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: admins
    description: Secured Admin-only calls
  - name: developers
    description: Operations available to regular developers
paths:
  /map :
    get:
      summary: Get all Maps
      operationId: getAllMaps
      description: 
        get all existantes maps in the map
      parameters:
        - name: page
          in: query
          description: page number
          required: true
          schema:
            type: integer
            format: int32
        - name: size
          in: query
          description: number of elements
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: return all map
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      docs:
                        type: array
                        items:
                          $ref: '#/components/schemas/Map'
                      totalDocs:
                        type: integer
                        format: int32
                      offset:
                        type: integer
                        format: int32
                      limit:
                        type: integer
                        format: int32
                      totalPages:
                        type: integer
                        format: int32
                      page:
                        type: integer
                        format: int32
                      pagingCounter:
                        type: integer
                        format: int32
                      hasPrevPage:
                        type: boolean
                      hasNextPage:
                        type: boolean
                      prevPage:
                        type: integer
                        format: int32
                      nextPage:
                        type: integer
                        format: int32
                  
        '400':
          description: error message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                        
        "401":
          description: missing authentification
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: authentification required
    post:
      summary: adds a map
      operationId: addMap
      description: Adds sytem class to the map
      responses:
        '201':
          description: map created
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Map'
                  
        '400':
          description: error message
          content:
            application/json:
              schema:
                type: object
                properties:
                  messsage:
                    type: string
        "401":
          description: missing authentification
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: authentification required           
                   
      requestBody:
        content:
          application/json:
            schema: 
             type: object
             required:
              - startTime
              - periodicity
              - system
              - monitoringAct
             properties:
              id:
                type: string
                example: "60edffc2370e9734982cc555"
              estimation:
                type: number
                example: 50
              periodicity:
                type: number
                example: 50
              startTime:
                type: string
                example:  "2021-07-30T17:10:08.369+00:00"   
              task:
                type: string
                example: "60edffc2370e9734982cc555"
              system:
                type: string
                example: "60edffc2370e9734982cc555"
              monitoringAct:
                type: string
                example: "60edffc2370e9734982cc555" 
        description: Map item to add
  /map/{id}:
    get:
      summary: get a single map
      operationId: getOneMap
      description: get map by Id
      parameters: 
      - in: path 
        name : id
        required: true
        schema:
          type: string
      responses:
        "200":
          description: return specific map
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    data:
                    $ref: '#/components/schemas/Map'
        "400":
          description: error message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  
                
                    
        "401":
          description: missing authentification
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: authentification required
        "404":
          description: map not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: map not found       
    patch:
      summary: update a single map
      description: update one map
      operationId: updateMap
      parameters: 
        - in: path
          name: id
          required: true
          schema:
            type: string

      responses:
        "201":
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Map'
       
          description: "updated map"
        "400":
          description: error message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "401":
          description: missing authentification
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: authentification required
        "404":
          description: map not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: map not found
        "501":
          description: "no error displayed"
        
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                estimation:
                  type: number
                  example: 50
                periodicity:
                  type: number
                  example: 50
                startTime:
                  type: string
                  example:  "2021-07-30T17:10:08.369+00:00"   
                active:
                  type: boolean
                  example: true
                task:
                  type: string
                  example: "60edffc2370e9734982cc555"
                system:
                  type: string
                  example: "60edffc2370e9734982cc555"
                monitoringAct:
                  type: string
                  example: "60edffc2370e9734982cc555"
    delete:  
      summary: delete a single map
      description: delete one map
      operationId: deleteMap
      parameters: 
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Map'
          description: "deleted map"
        "400":
          description: "error message"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "401":
          description: missing authentification
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: authentification required
        "404":
          description: "no map found"
      
components:
  schemas:
    Map:
      type: object
      required:
        - id
        - estimation
        - active
        - startTime
      properties:
        id:
          type: string
          example: "60edffc2370e9734982cc555"
        estimation:
          type: number
          example: 50
        periodicity:
          type: number
          example: 50
        startTime:
          type: string
          example:  "2021-07-30T17:10:08.369+00:00"   
        active:
          type: boolean
          example: true
        task:
          type: string
          example: "60edffc2370e9734982cc555"
        system:
          type: string
          example: "60edffc2370e9734982cc555"
        monitoringAct:
          type: string
          example: "60edffc2370e9734982cc555"      
          
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/skander12354/map/1.0.0