openapi: 3.0.0
info:
  description: Monitoring Type API
  version: "1.0.0"
  title: Monitoring Type API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
tags:
  - name: admins
    description: Secured Admin-only calls
  - name: developers
    description: Operations available to regular developers
paths:
  /monitoringType:
    get:
      summary: Get all Monitoring Type
      operationId: getAllMonitoringType
      description: get all existantes Monitoring Type in the system
      parameters:
        - name: page
          in: query
          description: page number
          required: true
          schema:
            type: integer
            format: int32
        - name: size
          in: query
          description: number of elements
          required: true
          schema:
            type: integer
            format: int32
        - name: isActive
          in: query
          description: number of elements
          required: false
          schema:
            type: boolean
      responses:
        "200":
          description: return all Monitoring Type
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      docs:
                        type: array
                        items:
                          $ref: "#/components/schemas/MonitoringType"
                      totalDocs:
                        type: integer
                        format: int32
                      offset:
                        type: integer
                        format: int32
                      limit:
                        type: integer
                        format: int32
                      totalPages:
                        type: integer
                        format: int32
                      page:
                        type: integer
                        format: int32
                      pagingCounter:
                        type: integer
                        format: int32
                      hasPrevPage:
                        type: boolean
                      hasNextPage:
                        type: boolean
                      prevPage:
                        type: integer
                        format: int32
                      nextPage:
                        type: integer
                        format: int32
                  
        "400":
          description: error message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

        "401":
          description: missing authentification
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: authentification required
    post:
      summary: adds a Monitoring Type
      operationId: addMonitoringType
      description: Adds MonitoringType to the system
      responses:
        "201":
          description: MonitoringType created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MonitoringType"

        "400":
          description: error message
          content:
            application/json:
              schema:
                type: object
                properties:
                  messsage:
                    type: string
        "401":
          description: missing authentification
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: authentification required

      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - libelle
                - isActive
              properties:
                libelle:
                  type: string
                  example: libelle
                isActive:
                  type: boolean
                  example: true
        description: MonitoringType item to add

  /monitoringType/{id}:
    get:
      summary: get a single MonitoringType
      description: get by ID one MonitoringType
      operationId: getByIdMonitoringType
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "201":
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "#/components/schemas/MonitoringType"

          description: "updated MonitoringType"
        "400":
          description: error message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "401":
          description: missing authentification
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: authentification required
        "404":
          description: MonitoringType not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: MonitoringType not found
        "501":
          description: "no error displayed"

  /monitoringType/update/{id}:
    patch:
      summary: update a single MonitoringType
      description: update one MonitoringType
      operationId: updateMonitoringType
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string

      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MonitoringType"

          description: "updated MonitoringType"
        "400":
          description: error message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "401":
          description: missing authentification
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: authentification required
        "404":
          description: MonitoringType not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: MonitoringType not found
        "501":
          description: "no error displayed"

      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                libelle:
                  type: string
                  example: libelleExemple
                isActive:
                  type: string
                  example: true
  /monitoringType/delete/{id}:
    delete:
      summary: delete a single MonitoringType
      description: delete one MonitoringType
      operationId: deleteMonitoringType
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MonitoringType"

          description: "updated MonitoringType"
        "400":
          description: error message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "401":
          description: missing authentification
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: authentification required
        "404":
          description: MonitoringType not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: MonitoringType not found
        "501":
          description: "no error displayed"

components:
  schemas:
    MonitoringType:
      type: object
      required:
        - id
        - libelle
        - isActive
      properties:
        id:
          type: string
          example: "60edffc2370e9734982cc555"
        libelle:
          type: string
          example: libelleExemple
        isActive:
          type: boolean
          example: true

servers:
  # Added by API Auto Mocking Plugin
  # Added by API Auto Mocking Plugin
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/skander12354/MonitoringActivity/1.0.0
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/skander12354/Type/1.0.0
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/skander12354/sysclass/1.0.0